apiVersion: v1
kind: Secret
metadata:
  name: loanflow-secrets
  namespace: loanflow
type: Opaque
stringData:
  jwt-secret:  "loanflow-prod-secret-change-this"
  db-host:     "postgres-service"
  db-user:     "postgres"
  db-password: "postgres"
  smtp-host:   "smtp.gmail.com"
  smtp-user:   ""
  smtp-pass:   ""
